<?php

/**
 * Verified inspection centers + main headquarters.
 * Source: CCTs of NACHO.docx — see docs/CENTERS_DATA.md
 */
return [

    'headquarters' => [
        'label_en' => 'Main Headquarter',
        'label_fr' => 'Siège principal',
        'address' => 'Atuakum Mankon, Bamenda, Cameroon',
        'postal_box' => 'P.O. Box 100 Bamenda',
        'email' => 'nachovehicletestingstation@yahoo.com',
        'phones' => [
            '(+237) 675615478',
            '(+237) 656901833',
            '(+237) 677789391',
        ],
        'phone_primary' => '(+237) 675615478',
        'phone_primary_tel' => '+237675615478',
    ],

    'centers' => [
        [
            'slug' => 'nacho-yaounde',
            'name' => 'NACHO Yaounde',
            'city' => 'Yaounde',
            'region' => 'Centre',
            'status' => 'operational',
            'address' => 'Mendong Market, Yaounde',
            'landmark' => 'Mendong market',
            'email' => 'navetescoyaounde@gmail.com',
            'phones' => ['(+237) 675117327', '(+237) 656901833'],
            'latitude' => 3.837496,
            'longitude' => 11.473015,
            'hours_en' => 'Weekdays 7:30 AM–6:00 PM · Sat. & public holidays 7:30 AM–4:00 PM',
            'hours_fr' => 'Jours ouvrables 7h30–18h00 · Sam. et jours fériés 7h30–16h00',
            'hours_lines_en' => ['7:30 AM – 6:00 PM (Mon–Fri)', '7:30 AM – 4:00 PM (Sat & Holidays)'],
            'hours_lines_fr' => ['7h30 – 18h00 (lun.–ven.)', '7h30 – 16h00 (sam. et jours fériés)'],
            'services' => [
                'periodic-technical-inspection',
                'light-vehicle-inspection',
                'counter-visit-re-inspection',
                'heavy-vehicle-inspection',
                'pre-purchase-inspection',
            ],
            'booking_key' => 'yaounde',
            'maps_url' => 'https://www.google.com/maps?q=3.837496,11.473015',
        ],
        [
            'slug' => 'nacho-nkwen-bamenda',
            'name' => 'NACHO Nkwen-Bamenda',
            'city' => 'Bamenda',
            'region' => 'Northwest',
            'status' => 'operational',
            'address' => 'NTEFINKI Quarter Mile 6, Nkwen',
            'landmark' => 'NTEFINKI Quarter mile 6 Nkwen',
            'email' => 'nachovehicletestingstation@yahoo.com',
            'phones' => ['(+237) 674036182', '(+237) 696130530'],
            'latitude' => 6.000978,
            'longitude' => 10.206111,
            'hours_en' => 'Monday–Saturday 8:00 AM–4:00 PM',
            'hours_fr' => 'Lundi–samedi 8h00–16h00',
            'hours_lines_en' => ['8:00 AM – 4:00 PM (Mon–Sat)'],
            'hours_lines_fr' => ['8h00 – 16h00 (lun.–sam.)'],
            'services' => [
                'periodic-technical-inspection',
                'light-vehicle-inspection',
                'heavy-vehicle-inspection',
                'counter-visit-re-inspection',
                'pre-purchase-inspection',
            ],
            'booking_key' => 'nkwen-bamenda',
            'maps_url' => 'https://www.google.com/maps?q=6.000978,10.206111',
        ],
        [
            'slug' => 'nacho-mankon-bamenda',
            'name' => 'NACHO Nacho-Bamenda',
            'name_suffix_en' => '/ Headquarters',
            'name_suffix_fr' => '/ Siège',
            'city' => 'Bamenda',
            'region' => 'Northwest',
            'status' => 'operational',
            'is_headquarters' => true,
            'address' => 'Atuakum Mankon, Bamenda',
            'postal_address' => 'P.O. Box 100 Bamenda',
            'landmark' => 'Atuakum Mankon',
            'email' => 'nachovehicletestingstation@yahoo.com',
            'phones' => ['(+237) 675615478', '(+237) 656901833', '(+237) 677789391'],
            'latitude' => 5.9418158,
            'longitude' => 10.1493449,
            'hours_en' => 'Monday–Saturday 8:00 AM–4:00 PM',
            'hours_fr' => 'Lundi–samedi 8h00–16h00',
            'hours_lines_en' => ['8:00 AM – 4:00 PM (Mon–Sat)'],
            'hours_lines_fr' => ['8h00 – 16h00 (lun.–sam.)'],
            'institutional_label_en' => 'NACHO Administrative Headquarters',
            'institutional_label_fr' => 'Siège administratif NACHO',
            'support_note_en' => 'This location serves as both an operational vehicle inspection center and NACHO\'s principal administrative headquarters.',
            'support_note_fr' => 'Ce site sert à la fois de centre opérationnel d\'inspection automobile et de siège administratif principal de NACHO.',
            'services' => [
                'periodic-technical-inspection',
                'light-vehicle-inspection',
                'heavy-vehicle-inspection',
                'counter-visit-re-inspection',
                'pre-purchase-inspection',
            ],
            'booking_key' => 'nacho-bamenda',
            'maps_url' => 'https://www.google.com/maps?q=5.9418158,10.1493449',
        ],
        [
            'slug' => 'nacho-douala',
            'name' => 'NACHO Douala',
            'name_suffix_en' => '(Coming soon)',
            'name_suffix_fr' => '(Bientôt disponible)',
            'city' => 'Douala',
            'region' => 'Littoral',
            'status' => 'under_construction',
            'address' => null,
            'landmark' => null,
            'email' => null,
            'phones' => [],
            'latitude' => null,
            'longitude' => null,
            'hours_en' => null,
            'hours_fr' => null,
            'maps_url' => null,
            'expansion_phase_en' => 'Equipment Installation',
            'expansion_phase_fr' => 'Installation des équipements',
            'expansion_target_en' => 'Before November 2026',
            'expansion_target_fr' => 'Avant novembre 2026',
            'expansion_last_updated_en' => 'June 2026',
            'expansion_last_updated_fr' => 'Juin 2026',
        ],
        [
            'slug' => 'nacho-kumba',
            'name' => 'NACHO Kumba',
            'name_suffix_en' => '(coming soon)',
            'name_suffix_fr' => '(bientôt disponible)',
            'city' => 'Kumba',
            'region' => 'Southwest',
            'status' => 'under_construction',
            'address' => null,
            'landmark' => null,
            'email' => null,
            'phones' => [],
            'latitude' => null,
            'longitude' => null,
            'hours_en' => null,
            'hours_fr' => null,
            'maps_url' => null,
            'expansion_phase_en' => 'Civil Works in Progress',
            'expansion_phase_fr' => 'Travaux de génie civil en cours',
            'expansion_target_en' => 'Before November 2026',
            'expansion_target_fr' => 'Avant novembre 2026',
            'expansion_last_updated_en' => 'June 2026',
            'expansion_last_updated_fr' => 'Juin 2026',
        ],
    ],

];
