<?php

/**
 * Homepage static content (Step 6). Copy in lang/{locale}/home.php.
 */
return [

    'services' => [
        ['key' => 'periodic', 'slug' => 'periodic-inspection', 'icon' => 'clipboard-check', 'bookable' => true],
        ['key' => 'light', 'slug' => 'light-vehicles', 'icon' => 'car-front', 'bookable' => true],
        ['key' => 'heavy', 'slug' => 'heavy-vehicles', 'icon' => 'truck', 'bookable' => true],
        ['key' => 'counter', 'slug' => 'counter-visit', 'icon' => 'refresh-cw', 'bookable' => true],
        ['key' => 'pre_purchase', 'slug' => 'pre-purchase', 'icon' => 'scan-search', 'bookable' => true],
        ['key' => 'road_safety', 'slug' => 'road-safety', 'icon' => 'shield-check', 'bookable' => false],
    ],

    'tariff_categories' => [
        ['id' => 'private', 'label_en' => 'Private car', 'label_fr' => 'Véhicule particulier'],
        ['id' => 'taxi', 'label_en' => 'Taxi', 'label_fr' => 'Taxi'],
        ['id' => 'pickup', 'label_en' => 'Pickup', 'label_fr' => 'Pick-up'],
        ['id' => 'bus', 'label_en' => 'Bus', 'label_fr' => 'Bus'],
        ['id' => 'truck', 'label_en' => 'Truck', 'label_fr' => 'Camion'],
        ['id' => 'other', 'label_en' => 'Other', 'label_fr' => 'Autre'],
    ],

    'tariff_preview' => [
        [
            'number' => 1,
            'filter_id' => 'taxi',
            'category_en' => 'Category A',
            'category_fr' => 'Catégorie A',
            'vehicle_type_en' => 'Taxi / Driving school',
            'vehicle_type_fr' => 'Taxi / Auto-école',
            'price' => '4 900 FCFA',
            'validity_en' => '03 months',
            'validity_fr' => '03 mois',
            'test_type_en' => 'All',
            'test_type_fr' => 'Tous',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 2,
            'filter_id' => 'private',
            'category_en' => 'Category B',
            'category_fr' => 'Catégorie B',
            'vehicle_type_en' => 'Passenger vehicle',
            'vehicle_type_fr' => 'Véhicule de tourisme',
            'price' => '17 900 FCFA',
            'validity_en' => '12 months',
            'validity_fr' => '12 mois',
            'test_type_en' => 'All',
            'test_type_fr' => 'Tous',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 3,
            'filter_id' => 'pickup',
            'category_en' => 'Category B1',
            'category_fr' => 'Catégorie B1',
            'vehicle_type_en' => 'Pickup 3.5 T / Light utility vehicles',
            'vehicle_type_fr' => 'Pickup 3,5 T / Véhicules utilitaires légers',
            'price' => '15 500 FCFA',
            'validity_en' => '06 months',
            'validity_fr' => '06 mois',
            'test_type_en' => 'All',
            'test_type_fr' => 'Tous',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 4,
            'filter_id' => 'bus',
            'category_en' => 'Category C < 3.5T',
            'category_fr' => 'Catégorie C < 3,5T',
            'vehicle_type_en' => 'Minibus',
            'vehicle_type_fr' => 'Mini-bus',
            'price' => '15 500 FCFA',
            'validity_en' => '03 months',
            'validity_fr' => '03 mois',
            'test_type_en' => 'All',
            'test_type_fr' => 'Tous',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 5,
            'filter_id' => 'bus',
            'category_en' => 'Category C',
            'category_fr' => 'Catégorie C',
            'vehicle_type_en' => 'Large bus / Coaster',
            'vehicle_type_fr' => 'Grand bus / Coaster',
            'price' => '19 080 FCFA',
            'validity_en' => '03 months',
            'validity_fr' => '03 mois',
            'test_type_en' => 'All except Suspension',
            'test_type_fr' => 'Tous sauf suspension',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 6,
            'filter_id' => 'truck',
            'category_en' => 'Category D',
            'category_fr' => 'Catégorie D',
            'vehicle_type_en' => 'Trucks / tractors / semi-trailers / heavy utility vehicles',
            'vehicle_type_fr' => 'Camions / Tracteurs / Sémi-remorques / Véhicules utilitaires lourds',
            'price' => '26 235 FCFA',
            'validity_en' => '06 months',
            'validity_fr' => '06 mois',
            'test_type_en' => 'All except Suspension',
            'test_type_fr' => 'Tous sauf suspension',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
        [
            'number' => 7,
            'filter_id' => 'other',
            'category_en' => 'Category D',
            'category_fr' => 'Catégorie D',
            'vehicle_type_en' => 'Other machinery',
            'vehicle_type_fr' => 'Autres engins',
            'price' => '41 750 FCFA',
            'validity_en' => '06 months',
            'validity_fr' => '06 mois',
            'test_type_en' => 'All except Suspension',
            'test_type_fr' => 'Tous sauf suspension',
            'documents_en' => 'Registration, insurance (see full tariffs page)',
            'documents_fr' => 'Carte grise, assurance (voir page Tarifs)',
        ],
    ],

];
